services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/dotnet:9.0
    container_name: alk-devcontainer
    working_dir: /workspaces/alk-stack
    command: sleep infinity
    volumes:
      - ..:/workspaces/alk-stack:cached
      - /var/run/docker.sock:/var/run/docker.sock
